### PR TITLE
Use toolbar left/right arrows for prev/next or back/forward (according to options)

### PR DESCRIPTION
**Pull request by shaiay**
Solves Issue #657

### CODE REVIEW

**Comment by kjk** [comment]
Thanks for the PR but I don't want to do it this way.

Adding one more setting to change how a program works is not a viable long-term strategy. Every additional setting makes the program a little bit worse and all other settings harder to find.

This is not to say I'm opposed to exposing back/forward in toolbar or some other easily accessible way but doing it right is exponentially harder than adding another setting.

**Comment by shaiay** [comment]
Do you have any thoughts on how to do it right?

**Comment by kjk** [comment]
Yes, but it's rather involved.

First, the toolbar itself needs to be more flexible. Currently the icons are in a bitmap. We need to be able to use vector icons (see https://github.com/sumatrapdfreader/sumatrapdf/issues/734) so that we can easily add more icons for more operations.

Second, make the toolbar configurable in settings file i.e. allow people to define a custom order by specifying order of icon/command associated with the icon.

**Comment by shaiay** [comment]
I'm afraid this is too big a project for me right now. 
My fork is always available if someone needs this very specific functionality and can't wait until it is implemented right.

**Comment by shaiay** [comment]
There seems to be a standard way to make a configurable toolbar:
https://msdn.microsoft.com/en-us/library/windows/desktop/hh298385(v=vs.85).aspx
This does not however move us away from bitmap icons

**Pull request closed without merging**
