### PR TITLE
PDF: Relax page type check (Fix issue #619)

### PR DESCRIPTION
**Pull request by libdor**

### CODE REVIEW

**Comment by kjk** [comment]
Thanks for the fix!
Even better solution would be to update to latest mupdf, but that's a lot of work due to api changes.

**Comment by libdor** [comment]
Do you want me to update to the latest mupdf?

**Comment by kjk** [comment]
That would be great. 

Beware that this might get complicated. Not only mupdf API have changed but mupdf also uses newer dependencies (like freetype, jbig2dec etc.) so those might require updating as well. I think they also added harfbuzz as dependency, so it would have to be added as well.

We also had some custom patches against those librarries (see ext/_patches directory). Some of those might not be needed anymore but some might require re-adding).

In case you're unfamiliar with build system, see https://www.sumatrapdfreader.org/docs/Our-build-system-3114db56b1a54b9bb026da6b92d36a80.html (in short, when adding/removing files or changing compilation flags, we modify premake5.lua and premake5.files.lua and re-run premake5 to generate visual studio projects in vs2015 and vs2017 directories).

(aside: I probably will require vs 2017 soon and vs 2015 will no longer be supported).

**Comment by libdor** [comment]
Finally,  can sit down to get some progress.

I have successfully compiled the mupdf 1.14.0 with the latest third party libraries, jbig2dec,  freetype2 and harfbuzz.

So,  can link the mupdf library and get the mutool. Now,  the big challenge is to fix all the issues in PdfCreator.cpp and PdfEngine.cpp, because the mupdf interface has changed so much.

Have you begun such work?  Any suggestions?

Jun

**Comment by kjk** [comment]
No, I haven't done any work on that so at this point, you know more than me. I would think that changes would be mostly mechanical but as I said, I'm guessing at this point.

If you share what you have so far (e.g. by putting it on a branch in your fork) I might find time to look at it and help.

**Comment by libdor** [comment]
I have pushed the changes to https://github.com/libdor/sumatrapdf/tree/mupdf-1.14.0

You may take a look and see what's the best way to integrate the changes.

________________________________

**Pull request merged**
