### PR TITLE
ctrl-dblclick on annotations is shortcut to edit

### PR DESCRIPTION
**Pull request by kerryland**
Users can now `ctrl-doubleclick` on an existing annotation and they will be taken to annotation editing. This is the same as the `"Edit Annotation"` context menu, but **much** more convenient to use when working with many annotations.

I'm less confident of this patch as it required more than one line of code. Also, I don't know how to communicate the _existence_ of this `ctrl-doubleclick` behaviour to the user. 

This partially fixes one of my gripes in bug#3638, but I will *try* and address the "needs a visual indicator to highlight the specific text" complaint in another pull request.

### CODE REVIEW

**Comment by GitHubRulesOK** [comment]
hmm untested but double click (unshifted) WAS invoke Synctex, more recently sullied by Double TAP as escape fulllview , so starting to wonder if there is a conflict in usages brewing?

**Comment by kerryland** [comment]
I'm happy to tweak things some more if you can provide some guidance

**Comment by kjk** [comment]
Thanks, I've used your code and tweaked it a bit in https://github.com/sumatrapdfreader/sumatrapdf/commit/5c63c533403e140ca8dc1051ef629a8166ad8ad2

@GitHubRulesOK the way it's written it shouldn't affect other use cases like selecting a word or synctex

Regarding exiting full screen: I'm open to other ideas for how to exit fullscreen mode with mouse / touch keyboard only. Double click was easy to implement.

**Comment by GitHubRulesOK** [comment]
@kjk 
I agree this case is different and I am off topic, so regards double tap interfeers with historic double click my suggestion was perhaps add a delay between click interval so 2 fast taps is as was but 2 slower taps is exit screen mode, not a good solution 
(non intuitive)  but reduces the overlapping actions to more useful to majority who will constantly invoke double click.

**Pull request closed without merging**
