### PR TITLE
Added vertical space before and after paragraphs

### LINKED ISSUE #376: Missing Space Between Paragraphs in "ePub" files
It's very hard to read "ePub" files in "SumatraPDF" because of the missing space between paragraphs. It would be great if you could fix this issue.

Thanks

A.T

### PR DESCRIPTION
**Pull request by sambhare**
Fixed #376 

Also changed default monospace font from Courier New to Lucida Console, changed default heading font to Arial. (Please reject these changes if necessary, although IMHO epubs look better this way.)

### CODE REVIEW

**Comment by sambhare** [comment]
Should be good now after my latest commit?

**Comment by kjk** [comment]
Thanks, looks reasonable, I'll take a closer look later today.

**Comment by kjk** [comment]
Thanks for the PR!

**Comment by sambhare** [comment]
Thanks for merging it. (My first PR ever!)

**Comment by 3N4N** [comment]
@sambhare @kjk Could we get indented paragraphs, like books normally have, instead of line-spaced paragraphs like blogs?

**Comment by GitHubRulesOK** [comment]
@3N4N 
the ePub engine has changed much over the 5 years since this custom change.
As far as I know this code change is no longer used (moving forwards for ePub) as that format is now handled by MuPDF so such changes would need to be in MuPDF or its related.css

**Pull request merged**
