### PR TITLE
New Brazilian Portuguese translations

### PR DESCRIPTION
**Pull request by marcoscmonteiro**
Adding new translations for Brazilian Portuguese related to annotations

### CODE REVIEW

**Comment by kjk** [comment]
Thanks, but to contribute translation you need to use http://www.apptranslator.org/app/SumatraPDF/br

The source code is generated from http://www.apptranslator.org

**Comment by marcoscmonteiro** [comment]
Done!

**Comment by kjk** [comment]
thanks! I've updated the translations

**Comment by espettia** [comment]
I've changed some Spanish translations most of them following AReader translations.

**Pull request closed without merging**
